/**
 * STATIC AUTOSUGGEST DATA
 * Pre-computed location and villa data for instant search suggestions
 *
 * To regenerate villa data from Salesforce, run:
 * npm run generate:autosuggest
 *
 * Note: Countries, regions, and towns are manually curated from the
 * location hierarchy defined in country-regions-config.ts
 */

export interface LocationItem {
  id: string;
  label: string;
  slug: string;
  type: 'country' | 'region' | 'town';
}

export interface VillaItem {
  id: string;
  name: string;
  slug: string;
}

// Countries (8 total)
export const COUNTRIES: LocationItem[] = [
  { id: 'country-spain', label: 'Spain', slug: 'spain', type: 'country' },
  { id: 'country-balearics', label: 'Balearics', slug: 'balearics', type: 'country' },
  { id: 'country-croatia', label: 'Croatia', slug: 'croatia', type: 'country' },
  { id: 'country-italy', label: 'Italy', slug: 'italy', type: 'country' },
  { id: 'country-greece', label: 'Greece', slug: 'greece', type: 'country' },
  { id: 'country-france', label: 'France', slug: 'france', type: 'country' },
  { id: 'country-portugal', label: 'Portugal', slug: 'portugal', type: 'country' },
  { id: 'country-turkey', label: 'Turkey', slug: 'turkey', type: 'country' },
];

// Regions (27 total)
export const REGIONS: LocationItem[] = [
  // Spain
  { id: 'region-galicia', label: 'Galicia', slug: 'galicia', type: 'region' },
  { id: 'region-costa-blanca', label: 'Costa Blanca', slug: 'costa-blanca', type: 'region' },
  { id: 'region-andalucia', label: 'Andalucia', slug: 'andalucia', type: 'region' },
  { id: 'region-catalunya', label: 'Catalunya', slug: 'catalunya', type: 'region' },
  // Balearics
  { id: 'region-mallorca', label: 'Mallorca', slug: 'mallorca', type: 'region' },
  { id: 'region-menorca', label: 'Menorca', slug: 'menorca', type: 'region' },
  // Croatia
  { id: 'region-dubrovnik', label: 'Dubrovnik', slug: 'dubrovnik', type: 'region' },
  { id: 'region-istria', label: 'Istria', slug: 'istria', type: 'region' },
  // Italy
  { id: 'region-lazio', label: 'Lazio', slug: 'lazio', type: 'region' },
  { id: 'region-puglia', label: 'Puglia', slug: 'puglia', type: 'region' },
  { id: 'region-tuscany', label: 'Tuscany', slug: 'tuscany', type: 'region' },
  { id: 'region-umbria', label: 'Umbria', slug: 'umbria', type: 'region' },
  // Greece
  { id: 'region-corfu', label: 'Corfu', slug: 'corfu', type: 'region' },
  { id: 'region-crete', label: 'Crete', slug: 'crete', type: 'region' },
  { id: 'region-lefkada', label: 'Lefkada', slug: 'lefkada', type: 'region' },
  { id: 'region-kefalonia', label: 'Kefalonia', slug: 'kefalonia', type: 'region' },
  { id: 'region-meganisi', label: 'Meganisi', slug: 'meganisi', type: 'region' },
  { id: 'region-parga', label: 'Parga', slug: 'parga', type: 'region' },
  { id: 'region-peloponnese', label: 'Peloponnese', slug: 'peloponnese', type: 'region' },
  { id: 'region-zakynthos', label: 'Zakynthos', slug: 'zakynthos', type: 'region' },
  // France
  { id: 'region-cote-d-azur', label: "Côte d'Azur", slug: 'cote-azur', type: 'region' },
  { id: 'region-languedoc', label: 'Languedoc', slug: 'languedoc', type: 'region' },
  { id: 'region-provence', label: 'Provence', slug: 'provence', type: 'region' },
  { id: 'region-south-west-france', label: 'South West France', slug: 'south-west-france', type: 'region' },
  // Portugal
  { id: 'region-costa-verde-minho', label: 'Costa Verde & Minho', slug: 'costa-verde-minho', type: 'region' },
  { id: 'region-algarve', label: 'Algarve', slug: 'algarve', type: 'region' },
  // Turkey
  { id: 'region-lycian-coast', label: 'Lycian Coast', slug: 'lycian-coast', type: 'region' },
];

// Towns - Generated from Salesforce (294 unique towns)
export const TOWNS: LocationItem[] = [
  { id: "town-afife", label: "Afife", slug: "afife", type: "town" },
  { id: "town-agia-effimia", label: "Agia Effimia", slug: "agia-effimia", type: "town" },
  { id: "town-agia-kyriaki", label: "Agia Kyriaki", slug: "agia-kyriaki", type: "town" },
  { id: "town-agia-paraskevi", label: "Agia Paraskevi", slug: "agia-paraskevi", type: "town" },
  { id: "town-agios-georgios", label: "Agios Georgios", slug: "agios-georgios", type: "town" },
  { id: "town-agios-ioannis", label: "Agios Ioannis", slug: "agios-ioannis", type: "town" },
  { id: "town-agios-nikolaos", label: "Agios Nikolaos", slug: "agios-nikolaos", type: "town" },
  { id: "town-agios-spyridon", label: "Agios Spyridon", slug: "agios-spyridon", type: "town" },
  { id: "town-ai-helis", label: "Ai Helis", slug: "ai-helis", type: "town" },
  { id: "town-aigua-blava", label: "Aigua Blava", slug: "aigua-blava", type: "town" },
  { id: "town-aigua-xelida", label: "Aigua Xelida", slug: "aigua-xelida", type: "town" },
  { id: "town-alaior", label: "Alaior", slug: "alaior", type: "town" },
  { id: "town-albufeira", label: "Albufeira", slug: "albufeira", type: "town" },
  { id: "town-alcaria-cova", label: "Alcaria Cova", slug: "alcaria-cova", type: "town" },
  { id: "town-alcudia", label: "Alcudia", slug: "alcudia", type: "town" },
  { id: "town-alignan-du-vent", label: "Alignan-du-Vent", slug: "alignan-du-vent", type: "town" },
  { id: "town-ammoudi", label: "Ammoudi", slug: "ammoudi", type: "town" },
  { id: "town-anthousa-village", label: "Anthousa Village", slug: "anthousa-village", type: "town" },
  { id: "town-antipata", label: "Antipata", slug: "antipata", type: "town" },
  { id: "town-apano-stalos", label: "Apano Stalos", slug: "apano-stalos", type: "town" },
  { id: "town-apolisi", label: "Apolisi", slug: "apolisi", type: "town" },
  { id: "town-arcos-de-la-frontera", label: "Arcos de la Frontera", slug: "arcos-de-la-frontera", type: "town" },
  { id: "town-arcozelo", label: "Arcozelo", slug: "arcozelo", type: "town" },
  { id: "town-aspra", label: "Aspra", slug: "aspra", type: "town" },
  { id: "town-assos", label: "Assos", slug: "assos", type: "town" },
  { id: "town-aumes", label: "Aumes", slug: "aumes", type: "town" },
  { id: "town-balcon-al-mar", label: "Balcon al Mar", slug: "balcon-al-mar", type: "town" },
  { id: "town-baleyssagues", label: "Baleyssagues", slug: "baleyssagues", type: "town" },
  { id: "town-banyalbufar", label: "Banyalbufar", slug: "banyalbufar", type: "town" },
  { id: "town-barbati", label: "Barbati", slug: "barbati", type: "town" },
  { id: "town-barral", label: "Barral", slug: "barral", type: "town" },
  { id: "town-barrio", label: "Bárrio", slug: "barrio", type: "town" },
  { id: "town-bataji", label: "Bataji", slug: "bataji", type: "town" },
  { id: "town-begur", label: "Begur", slug: "begur", type: "town" },
  { id: "town-benamahoma", label: "Benamahoma", slug: "benamahoma", type: "town" },
  { id: "town-bessan", label: "Bessan", slug: "bessan", type: "town" },
  { id: "town-binibeca", label: "Binibeca", slug: "binibeca", type: "town" },
  { id: "town-binidali", label: "Binidali", slug: "binidali", type: "town" },
  { id: "town-biot", label: "Biot", slug: "biot", type: "town" },
  { id: "town-bolsena", label: "Bolsena", slug: "bolsena", type: "town" },
  { id: "town-boukari", label: "Boukari", slug: "boukari", type: "town" },
  { id: "town-buger", label: "Buger", slug: "buger", type: "town" },
  { id: "town-cabracao", label: "Cabração", slug: "cabracao", type: "town" },
  { id: "town-cabrieres-d-avignon", label: "Cabrières d'Avignon", slug: "cabrieres-d-avignon", type: "town" },
  { id: "town-cala-canyelles", label: "Cala Canyelles", slug: "cala-canyelles", type: "town" },
  { id: "town-cala-d-or", label: "Cala d'Or", slug: "cala-d-or", type: "town" },
  { id: "town-cala-egos", label: "Cala Egos", slug: "cala-egos", type: "town" },
  { id: "town-cala-llonga", label: "Cala Llonga", slug: "cala-llonga", type: "town" },
  { id: "town-cala-mondrago", label: "Cala Mondrago", slug: "cala-mondrago", type: "town" },
  { id: "town-cala-morell", label: "Cala Morell", slug: "cala-morell", type: "town" },
  { id: "town-cala-sa-nau", label: "Cala Sa Nau", slug: "cala-sa-nau", type: "town" },
  { id: "town-cala-sa-nau-cala-mitjana", label: "Cala Sa Nau/Cala Mitjana", slug: "cala-sa-nau-cala-mitjana", type: "town" },
  { id: "town-cala-san-vicenc", label: "Cala San Vicenç", slug: "cala-san-vicenc", type: "town" },
  { id: "town-calella-llafranc", label: "Calella/Llafranc", slug: "calella-llafranc", type: "town" },
  { id: "town-calheiros", label: "Calheiros", slug: "calheiros", type: "town" },
  { id: "town-callas", label: "Callas", slug: "callas", type: "town" },
  { id: "town-carataunas", label: "Carataunas", slug: "carataunas", type: "town" },
  { id: "town-caromb", label: "Caromb", slug: "caromb", type: "town" },
  { id: "town-carovigno", label: "Carovigno", slug: "carovigno", type: "town" },
  { id: "town-casa-de-campo", label: "Casa de Campo", slug: "casa-de-campo", type: "town" },
  { id: "town-castelfiorentino", label: "Castelfiorentino", slug: "castelfiorentino", type: "town" },
  { id: "town-castell-platja-d-aro", label: "Castell-Platja d'Aro", slug: "castell-platja-d-aro", type: "town" },
  { id: "town-castelnau-de-levis", label: "Castelnau-de-Lévis", slug: "castelnau-de-levis", type: "town" },
  { id: "town-castelnau-de-montmiral", label: "Castelnau-de-Montmiral", slug: "castelnau-de-montmiral", type: "town" },
  { id: "town-castiglion-fiorentino", label: "Castiglion Fiorentino", slug: "castiglion-fiorentino", type: "town" },
  { id: "town-castillonnes", label: "Castillonnès", slug: "castillonnes", type: "town" },
  { id: "town-caux", label: "Caux", slug: "caux", type: "town" },
  { id: "town-cazals", label: "Cazals", slug: "cazals", type: "town" },
  { id: "town-ceilan", label: "Ceilan", slug: "ceilan", type: "town" },
  { id: "town-collobrieres", label: "Collobrières", slug: "collobrieres", type: "town" },
  { id: "town-combarro", label: "Combarro", slug: "combarro", type: "town" },
  { id: "town-cortona", label: "Cortona", slug: "cortona", type: "town" },
  { id: "town-costa-nova", label: "Costa Nova", slug: "costa-nova", type: "town" },
  { id: "town-coves-noves", label: "Coves Noves", slug: "coves-noves", type: "town" },
  { id: "town-cumbre-del-sol", label: "Cumbre del Sol", slug: "cumbre-del-sol", type: "town" },
  { id: "town-defaranata", label: "Defaranata", slug: "defaranata", type: "town" },
  { id: "town-devillac", label: "Dévillac", slug: "devillac", type: "town" },
  { id: "town-donas", label: "Donas", slug: "donas", type: "town" },
  { id: "town-dragotina", label: "Dragotina", slug: "dragotina", type: "town" },
  { id: "town-dubravka", label: "Dubravka", slug: "dubravka", type: "town" },
  { id: "town-duravel", label: "Duravel", slug: "duravel", type: "town" },
  { id: "town-el-bosque", label: "El Bosque", slug: "el-bosque", type: "town" },
  { id: "town-el-gastor", label: "El Gastor", slug: "el-gastor", type: "town" },
  { id: "town-el-portet", label: "El Portet", slug: "el-portet", type: "town" },
  { id: "town-el-santiscal", label: "El Santiscal", slug: "el-santiscal", type: "town" },
  { id: "town-estoi", label: "Estoi", slug: "estoi", type: "town" },
  { id: "town-eygalieres", label: "Eygalières", slug: "eygalieres", type: "town" },
  { id: "town-facha", label: "Facha", slug: "facha", type: "town" },
  { id: "town-felanitx", label: "Felanitx", slug: "felanitx", type: "town" },
  { id: "town-fiskardo", label: "Fiskardo", slug: "fiskardo", type: "town" },
  { id: "town-floressas", label: "Floressas", slug: "floressas", type: "town" },
  { id: "town-fontao", label: "Fontao", slug: "fontao", type: "town" },
  { id: "town-fterno", label: "Fterno", slug: "fterno", type: "town" },
  { id: "town-gaglietole", label: "Gaglietole", slug: "gaglietole", type: "town" },
  { id: "town-gale", label: "Gale", slug: "gale", type: "town" },
  { id: "town-gastouri", label: "Gastouri", slug: "gastouri", type: "town" },
  { id: "town-gemeira", label: "Gemeira", slug: "gemeira", type: "town" },
  { id: "town-gerakas", label: "Gerakas", slug: "gerakas", type: "town" },
  { id: "town-gialova", label: "Gialova", slug: "gialova", type: "town" },
  { id: "town-giove", label: "Giove", slug: "giove", type: "town" },
  { id: "town-gondufe", label: "Gondufe", slug: "gondufe", type: "town" },
  { id: "town-gordes", label: "Gordes", slug: "gordes", type: "town" },
  { id: "town-gouvia", label: "Gouvia", slug: "gouvia", type: "town" },
  { id: "town-grasse", label: "Grasse", slug: "grasse", type: "town" },
  { id: "town-grazalema", label: "Grazalema", slug: "grazalema", type: "town" },
  { id: "town-grimaud", label: "Grimaud", slug: "grimaud", type: "town" },
  { id: "town-gruda", label: "Gruda", slug: "gruda", type: "town" },
  { id: "town-guia", label: "Guia", slug: "guia", type: "town" },
  { id: "town-halikounas", label: "Halikounas", slug: "halikounas", type: "town" },
  { id: "town-hio", label: "Hio", slug: "hio", type: "town" },
  { id: "town-islamlar", label: "Islamlar", slug: "islamlar", type: "town" },
  { id: "town-jesus-pobre", label: "Jesus Pobre", slug: "jesus-pobre", type: "town" },
  { id: "town-kaligata", label: "Kaligata", slug: "kaligata", type: "town" },
  { id: "town-kalipado", label: "Kalipado", slug: "kalipado", type: "town" },
  { id: "town-kalkan", label: "Kalkan", slug: "kalkan", type: "town" },
  { id: "town-karavados", label: "Karavados", slug: "karavados", type: "town" },
  { id: "town-kas-peninsula", label: "Kas Peninsula", slug: "kas-peninsula", type: "town" },
  { id: "town-kassiopi", label: "Kassiopi", slug: "kassiopi", type: "town" },
  { id: "town-katapodata", label: "Katapodata", slug: "katapodata", type: "town" },
  { id: "town-katomeri", label: "Katomeri", slug: "katomeri", type: "town" },
  { id: "town-katsarata", label: "Katsarata", slug: "katsarata", type: "town" },
  { id: "town-kerasia", label: "Kerasia", slug: "kerasia", type: "town" },
  { id: "town-khalikeri", label: "Khalikerí", slug: "khalikeri", type: "town" },
  { id: "town-kokkini", label: "Kokkini", slug: "kokkini", type: "town" },
  { id: "town-korakies", label: "Korakies", slug: "korakies", type: "town" },
  { id: "town-la-borie-blanche", label: "La Borie Blanche", slug: "la-borie-blanche", type: "town" },
  { id: "town-la-font", label: "La Font", slug: "la-font", type: "town" },
  { id: "town-la-fouillade", label: "La Fouillade", slug: "la-fouillade", type: "town" },
  { id: "town-la-pera", label: "La Pera", slug: "la-pera", type: "town" },
  { id: "town-la-theze", label: "La Theze", slug: "la-theze", type: "town" },
  { id: "town-lagopodo", label: "Lagopodo", slug: "lagopodo", type: "town" },
  { id: "town-landerrouat", label: "Landerrouat", slug: "landerrouat", type: "town" },
  { id: "town-le-brel", label: "Le Brel", slug: "le-brel", type: "town" },
  { id: "town-le-croce", label: "Le Croce", slug: "le-croce", type: "town" },
  { id: "town-le-fleix", label: "Le Fleix", slug: "le-fleix", type: "town" },
  { id: "town-le-tignet", label: "Le Tignet", slug: "le-tignet", type: "town" },
  { id: "town-le-trayas", label: "Le Trayas", slug: "le-trayas", type: "town" },
  { id: "town-lefkada-town", label: "Lefkada Town", slug: "lefkada-town", type: "town" },
  { id: "town-lezignan-la-cebe", label: "Lézignan la Cèbe", slug: "lezignan-la-cebe", type: "town" },
  { id: "town-libreros", label: "Libreros", slug: "libreros", type: "town" },
  { id: "town-llafranc", label: "Llafranc", slug: "llafranc", type: "town" },
  { id: "town-loule", label: "Loulé", slug: "loule", type: "town" },
  { id: "town-lourdas", label: "Lourdas", slug: "lourdas", type: "town" },
  { id: "town-loutses", label: "Loutses", slug: "loutses", type: "town" },
  { id: "town-lucignana", label: "Lucignana", slug: "lucignana", type: "town" },
  { id: "town-ludo", label: "Ludo", slug: "ludo", type: "town" },
  { id: "town-lugar-da-marasca", label: "Lugar da Marasca", slug: "lugar-da-marasca", type: "town" },
  { id: "town-maganos", label: "Maganos", slug: "maganos", type: "town" },
  { id: "town-maheri", label: "Maheri", slug: "maheri", type: "town" },
  { id: "town-makryotika", label: "Makryotika", slug: "makryotika", type: "town" },
  { id: "town-maleme", label: "Maleme", slug: "maleme", type: "town" },
  { id: "town-malhao", label: "Malhão", slug: "malhao", type: "town" },
  { id: "town-margon", label: "Margon", slug: "margon", type: "town" },
  { id: "town-martel", label: "Martel", slug: "martel", type: "town" },
  { id: "town-martillac", label: "Martillac", slug: "martillac", type: "town" },
  { id: "town-martina-franca", label: "Martina Franca", slug: "martina-franca", type: "town" },
  { id: "town-maruzini", label: "Maruzini", slug: "maruzini", type: "town" },
  { id: "town-maussane-les-alpilles", label: "Maussane Les Alpilles", slug: "maussane-les-alpilles", type: "town" },
  { id: "town-mauzac-et-grand-castang", label: "Mauzac-et-Grand Castang", slug: "mauzac-et-grand-castang", type: "town" },
  { id: "town-mercatale", label: "Mercatale", slug: "mercatale", type: "town" },
  { id: "town-metaxata", label: "Metaxata", slug: "metaxata", type: "town" },
  { id: "town-mihanici", label: "Mihanići", slug: "mihanici", type: "town" },
  { id: "town-mikri-mantineia", label: "Mikri Mantineia", slug: "mikri-mantineia", type: "town" },
  { id: "town-minies", label: "Minies", slug: "minies", type: "town" },
  { id: "town-mirandol-bourgnounac", label: "Mirandol-Bourgnounac", slug: "mirandol-bourgnounac", type: "town" },
  { id: "town-moledo-do-minho", label: "Moledo do Minho", slug: "moledo-do-minho", type: "town" },
  { id: "town-monclar-de-quercy", label: "Monclar-de-Quercy", slug: "monclar-de-quercy", type: "town" },
  { id: "town-mont-ras", label: "Mont Ras", slug: "mont-ras", type: "town" },
  { id: "town-montagnac-sur-lede", label: "Montagnac-sur-Lède", slug: "montagnac-sur-lede", type: "town" },
  { id: "town-montauroux", label: "Montauroux", slug: "montauroux", type: "town" },
  { id: "town-montcuq", label: "Montcuq", slug: "montcuq", type: "town" },
  { id: "town-montgo-national-park", label: "Montgo National Park", slug: "montgo-national-park", type: "town" },
  { id: "town-moreira", label: "Moreira", slug: "moreira", type: "town" },
  { id: "town-moreira-do-lima", label: "Moreira do Lima", slug: "moreira-do-lima", type: "town" },
  { id: "town-mosende", label: "Mosende", slug: "mosende", type: "town" },
  { id: "town-moussata", label: "Moussata", slug: "moussata", type: "town" },
  { id: "town-nasce", label: "Nasce", slug: "nasce", type: "town" },
  { id: "town-nissaki", label: "Nissaki", slug: "nissaki", type: "town" },
  { id: "town-noci", label: "Noci", slug: "noci", type: "town" },
  { id: "town-nydri", label: "Nydri", slug: "nydri", type: "town" },
  { id: "town-o-barro", label: "O Barro", slug: "o-barro", type: "town" },
  { id: "town-o-grove", label: "O Grove", slug: "o-grove", type: "town" },
  { id: "town-oia", label: "Oia", slug: "oia", type: "town" },
  { id: "town-olhos-d-agua", label: "Olhos d'Agua", slug: "olhos-d-agua", type: "town" },
  { id: "town-orgiva", label: "Orgiva", slug: "orgiva", type: "town" },
  { id: "town-ostuni", label: "Ostuni", slug: "ostuni", type: "town" },
  { id: "town-paciano", label: "Paciano", slug: "paciano", type: "town" },
  { id: "town-paderne", label: "Paderne", slug: "paderne", type: "town" },
  { id: "town-palmeira-de-faro", label: "Palmeira de Faro", slug: "palmeira-de-faro", type: "town" },
  { id: "town-paradou", label: "Paradou", slug: "paradou", type: "town" },
  { id: "town-parentis-en-born", label: "Parentis-en-Born", slug: "parentis-en-born", type: "town" },
  { id: "town-parga-town", label: "Parga Town", slug: "parga-town", type: "town" },
  { id: "town-petalidi", label: "Petalidi", slug: "petalidi", type: "town" },
  { id: "town-peymeinade", label: "Peymeinade", slug: "peymeinade", type: "town" },
  { id: "town-pezenas", label: "Pézenas", slug: "pezenas", type: "town" },
  { id: "town-pianello", label: "Pianello", slug: "pianello", type: "town" },
  { id: "town-pico-de-regalados", label: "Pico de Regalados", slug: "pico-de-regalados", type: "town" },
  { id: "town-pino-sol", label: "Pino Sol", slug: "pino-sol", type: "town" },
  { id: "town-pirgi", label: "Pirgi", slug: "pirgi", type: "town" },
  { id: "town-plan-d-orgon", label: "Plan-d'Orgon", slug: "plan-d-orgon", type: "town" },
  { id: "town-platanias", label: "Platanias", slug: "platanias", type: "town" },
  { id: "town-platja-de-pals", label: "Platja de Pals", slug: "platja-de-pals", type: "town" },
  { id: "town-playa-de-limens", label: "Playa de Limens", slug: "playa-de-limens", type: "town" },
  { id: "town-playa-de-pintens", label: "Playa de Pintens", slug: "playa-de-pintens", type: "town" },
  { id: "town-playa-de-santa-marta", label: "Playa de Santa Marta", slug: "playa-de-santa-marta", type: "town" },
  { id: "town-polemarchi", label: "Polemarchi", slug: "polemarchi", type: "town" },
  { id: "town-polignano-a-mare", label: "Polignano a Mare", slug: "polignano-a-mare", type: "town" },
  { id: "town-pollenca", label: "Pollenca", slug: "pollenca", type: "town" },
  { id: "town-pomport", label: "Pomport", slug: "pomport", type: "town" },
  { id: "town-ponte-de-lima", label: "Ponte de Lima", slug: "ponte-de-lima", type: "town" },
  { id: "town-port-de-pollenca", label: "Port de Pollenca", slug: "port-de-pollenca", type: "town" },
  { id: "town-porto-d-ave", label: "Porto d'Ave", slug: "porto-d-ave", type: "town" },
  { id: "town-portocolom", label: "Portocolom", slug: "portocolom", type: "town" },
  { id: "town-pozzo-della-chiana", label: "Pozzo della Chiana", slug: "pozzo-della-chiana", type: "town" },
  { id: "town-prats-du-perigord", label: "Prats-du-Périgord", slug: "prats-du-perigord", type: "town" },
  { id: "town-quinta-do-rosal", label: "Quinta do Rosal", slug: "quinta-do-rosal", type: "town" },
  { id: "town-radetici", label: "Radetici", slug: "radetici", type: "town" },
  { id: "town-radici", label: "Radici", slug: "radici", type: "town" },
  { id: "town-raxo", label: "Raxó", slug: "raxo", type: "town" },
  { id: "town-regencos", label: "Regencós", slug: "regencos", type: "town" },
  { id: "town-riba-de-ancora", label: "Riba de Ancora", slug: "riba-de-ancora", type: "town" },
  { id: "town-rieux-minervois", label: "Rieux-Minervois", slug: "rieux-minervois", type: "town" },
  { id: "town-roche-viejo", label: "Roche Viejo", slug: "roche-viejo", type: "town" },
  { id: "town-roda", label: "Roda", slug: "roda", type: "town" },
  { id: "town-ronda", label: "Ronda", slug: "ronda", type: "town" },
  { id: "town-roussillon", label: "Roussillon", slug: "roussillon", type: "town" },
  { id: "town-rustrel", label: "Rustrel", slug: "rustrel", type: "town" },
  { id: "town-sa-pobla", label: "Sa Pobla", slug: "sa-pobla", type: "town" },
  { id: "town-saint-antonin-du-var", label: "Saint Antonin-du-Var", slug: "saint-antonin-du-var", type: "town" },
  { id: "town-saint-didier", label: "Saint Didier", slug: "saint-didier", type: "town" },
  { id: "town-saint-maurice-de-lestapel", label: "Saint Maurice-de-Lestapel", slug: "saint-maurice-de-lestapel", type: "town" },
  { id: "town-saint-remy-de-provence", label: "Saint Rémy de Provence", slug: "saint-remy-de-provence", type: "town" },
  { id: "town-salvagnac", label: "Salvagnac", slug: "salvagnac", type: "town" },
  { id: "town-san-gimignano", label: "San Gimignano", slug: "san-gimignano", type: "town" },
  { id: "town-san-jose-del-valle", label: "San Jose del Valle", slug: "san-jose-del-valle", type: "town" },
  { id: "town-san-leo-bastia", label: "San Leo Bastia", slug: "san-leo-bastia", type: "town" },
  { id: "town-san-lorenzo-de-cardessar", label: "San Lorenzo de Cardessar", slug: "san-lorenzo-de-cardessar", type: "town" },
  { id: "town-san-pancrazio", label: "San Pancrazio", slug: "san-pancrazio", type: "town" },
  { id: "town-sant-lluis", label: "Sant Lluis", slug: "sant-lluis", type: "town" },
  { id: "town-sant-marti-d-empuries", label: "Sant Marti d'Empuries", slug: "sant-marti-d-empuries", type: "town" },
  { id: "town-santa-barbara-de-nexe", label: "Santa Bárbara de Nexe", slug: "santa-barbara-de-nexe", type: "town" },
  { id: "town-santa-catarina-fonte-do-bispo", label: "Santa Catarina Fonte do Bispo", slug: "santa-catarina-fonte-do-bispo", type: "town" },
  { id: "town-santa-margalida", label: "Santa Margalida", slug: "santa-margalida", type: "town" },
  { id: "town-santiago-de-compostela", label: "Santiago de Compostela", slug: "santiago-de-compostela", type: "town" },
  { id: "town-sao-rafael", label: "São Rafael", slug: "sao-rafael", type: "town" },
  { id: "town-sarlata", label: "Sarlata", slug: "sarlata", type: "town" },
  { id: "town-ses-mongetes", label: "Ses Mongetes", slug: "ses-mongetes", type: "town" },
  { id: "town-seyches", label: "Seyches", slug: "seyches", type: "town" },
  { id: "town-sisan", label: "Sisan", slug: "sisan", type: "town" },
  { id: "town-sivota", label: "Sivota", slug: "sivota", type: "town" },
  { id: "town-son-bou", label: "Son Bou", slug: "son-bou", type: "town" },
  { id: "town-son-parc", label: "Son Parc", slug: "son-parc", type: "town" },
  { id: "town-son-vent", label: "Son Vent", slug: "son-vent", type: "town" },
  { id: "town-spartia", label: "Spartia", slug: "spartia", type: "town" },
  { id: "town-spartohori", label: "Spartohori", slug: "spartohori", type: "town" },
  { id: "town-st-andre-de-najac", label: "St André-de-Najac", slug: "st-andre-de-najac", type: "town" },
  { id: "town-st-cezaire-sur-siagne", label: "St Cézaire sur Siagne", slug: "st-cezaire-sur-siagne", type: "town" },
  { id: "town-st-martin-de-beauville", label: "St Martin de Beauville", slug: "st-martin-de-beauville", type: "town" },
  { id: "town-st-paul-de-vence", label: "St Paul de Vence", slug: "st-paul-de-vence", type: "town" },
  { id: "town-stancija-blek", label: "Stancija Blek", slug: "stancija-blek", type: "town" },
  { id: "town-sveti-lovrec", label: "Sveti Lovrec", slug: "sveti-lovrec", type: "town" },
  { id: "town-tamariu", label: "Tamariu", slug: "tamariu", type: "town" },
  { id: "town-tavronitis-beach", label: "Tavronitis Beach", slug: "tavronitis-beach", type: "town" },
  { id: "town-teulada-moraira", label: "Teulada/Moraira", slug: "teulada-moraira", type: "town" },
  { id: "town-the-pine-walk", label: "The Pine Walk", slug: "the-pine-walk", type: "town" },
  { id: "town-tinjan", label: "Tinjan", slug: "tinjan", type: "town" },
  { id: "town-torre-soli-son-bou", label: "Torre Soli (Son Bou)", slug: "torre-soli-son-bou", type: "town" },
  { id: "town-torregentile", label: "Torregentile", slug: "torregentile", type: "town" },
  { id: "town-travassos", label: "Travassos", slug: "travassos", type: "town" },
  { id: "town-tsoukalades", label: "Tsoukalades", slug: "tsoukalades", type: "town" },
  { id: "town-valbonne", label: "Valbonne", slug: "valbonne", type: "town" },
  { id: "town-vall-de-colonya", label: "Vall de Colonya", slug: "vall-de-colonya", type: "town" },
  { id: "town-vanato", label: "Vanato", slug: "vanato", type: "town" },
  { id: "town-vasilikades", label: "Vasilikades", slug: "vasilikades", type: "town" },
  { id: "town-vasiliki", label: "Vasiliki", slug: "vasiliki", type: "town" },
  { id: "town-vasilikos", label: "Vasilikos", slug: "vasilikos", type: "town" },
  { id: "town-vatos", label: "Vatos", slug: "vatos", type: "town" },
  { id: "town-vejer-de-la-frontera", label: "Vejer de la Frontera", slug: "vejer-de-la-frontera", type: "town" },
  { id: "town-venade", label: "Venade", slug: "venade", type: "town" },
  { id: "town-vence", label: "Vence", slug: "vence", type: "town" },
  { id: "town-vigo", label: "Vigo", slug: "vigo", type: "town" },
  { id: "town-vila-de-prado", label: "Vila de Prado", slug: "vila-de-prado", type: "town" },
  { id: "town-vilacoba", label: "Vilacoba", slug: "vilacoba", type: "town" },
  { id: "town-vilamoura", label: "Vilamoura", slug: "vilamoura", type: "town" },
  { id: "town-vilarino-de-arriba", label: "Vilariño de Arriba", slug: "vilarino-de-arriba", type: "town" },
  { id: "town-vilas", label: "Vilas", slug: "vilas", type: "town" },
  { id: "town-villars", label: "Villars", slug: "villars", type: "town" },
  { id: "town-viros", label: "Viros", slug: "viros", type: "town" },
  { id: "town-visnjan", label: "Visnjan", slug: "visnjan", type: "town" },
  { id: "town-vitorino-das-donas", label: "Vitorino das Donas", slug: "vitorino-das-donas", type: "town" },
  { id: "town-xabia-javea", label: "Xabia (Javea)", slug: "xabia-javea", type: "town" },
  { id: "town-zahora", label: "Zahora", slug: "zahora", type: "town" },
];

// Villas - populated by generate:autosuggest script or manually
// These are loaded from Salesforce data
export const VILLAS: VillaItem[] = [];
