/**
 * PHASE 49: STRICT COUNTRY VALIDATION
 * Auto-generated from live Salesforce data via P_Property_Location__c
 *
 * Generated: 2026-01-13T12:35:12.838Z
 * Source: 529 villas with 2026 prices
 *
 * STRICT VALIDATION: Only 8 valid countries allowed
 * Valid Countries: Balearics, Spain, France, Croatia, Turkey, Greece, Italy, Portugal
 *
 * Hierarchy:
 * - Countries: 8 (strictly validated)
 * - Regions: 137 (includes formerly misclassified countries like Tuscany, Algarve)
 * - Towns: 274
 */

export interface LocationStructure {
  countries: string[];
  regions: string[];
  towns: string[];
}

export const STATIC_LOCATIONS: LocationStructure = {
  countries: [
    "Balearics",
    "Croatia",
    "France",
    "Greece",
    "Italy",
    "Portugal",
    "Spain",
    "Turkey"
  ],
  regions: [
    "Acharavi",
    "Aghios Stefanos",
    "Agia Effimia",
    "Alaior",
    "Albi",
    "Algarve",
    "Almancil",
    "Andalucia",
    "Arcos de la Frontera",
    "Arenal d'en Castell",
    "Assos",
    "Avithos",
    "Bagni di Lucca",
    "Barbati",
    "Benitachell",
    "Bergerac",
    "Binibeca",
    "Boliqueime",
    "Bordeaux",
    "Braga",
    "Ca's Concos",
    "Cala d'Or",
    "Calella de Palafrugell",
    "Calonge Area",
    "Caminha",
    "Cangas",
    "Carcassonne",
    "Carvoeiro",
    "Castillonnès",
    "Catalunya",
    "Cesantes",
    "Chania Area",
    "Ciutadella",
    "Conil de la Frontera",
    "Corfu",
    "Corfu Town",
    "Cortona",
    "Costa Blanca",
    "Costa Verde & Minho",
    "Côte d'Azur",
    "Crete",
    "Denia",
    "Deruta",
    "Dubrovnik",
    "Duras",
    "El Bosque",
    "Ermones",
    "Esposende",
    "Estoi",
    "Fiskardo",
    "Fterno",
    "Gale",
    "Galicia",
    "Gondomar",
    "Gordes",
    "Grasse",
    "Hio",
    "Istria",
    "Kalamata",
    "Kalipado",
    "Kalkan",
    "Kas",
    "Kefalonia",
    "Konavle Valley",
    "La Garde-Freinet",
    "Languedoc",
    "Lazio",
    "Lefkada",
    "Lefkimmi",
    "Les Arques",
    "Liznjan",
    "Lorgues",
    "Lucca",
    "Lycian Coast",
    "Machairado",
    "Mallorca",
    "Meganisi",
    "Menorca",
    "Messinia",
    "Miramont-de-Guyenne",
    "Mondariz Balneario",
    "Monflanquin",
    "Montcuq",
    "Motovun",
    "Najac",
    "Navarino Bay",
    "Negreira",
    "Nigran",
    "Nissaki",
    "Novigrad",
    "O Porriño",
    "Palafrugell Area",
    "Pals",
    "Parga",
    "Parga Town",
    "Peloponnese",
    "Perithea",
    "Pernes les Fontaines",
    "Perugia",
    "Pézenas",
    "Pollenca",
    "Ponte de Lima",
    "Port de Pollenca",
    "Povoa de Lanhoso",
    "Prats-du-Périgord",
    "Provence",
    "Rabastens",
    "Rethymno",
    "Saint Rémy de Provence",
    "Sainte Foy la Grande",
    "Sainte-Maxime",
    "Sami",
    "San Stefanos",
    "Santanyi",
    "Sanxenxo and Surrounding Villages",
    "South West France",
    "St Cézaire sur Siagne",
    "Stoupa",
    "Sveti Lovrec",
    "Svetvincenat",
    "Svoronata",
    "Tamariu",
    "Tavira",
    "Tavronitis",
    "Teulada/Moraira",
    "Todi",
    "Trapezaki",
    "Tuscany",
    "Umbria",
    "Vasilikos",
    "Vejer de la Frontera",
    "Vila Praia de Ancora",
    "Vila Verde",
    "Villars",
    "Villeréal",
    "Xabia (Javea)",
    "Zakynthos"
  ],
  towns: [
    "Afife",
    "Agia Effimia",
    "Agia Kyriaki",
    "Agia Paraskevi",
    "Agios Georgios",
    "Agios Ioannis",
    "Agios Nikolaos",
    "Agios Spyridon",
    "Ai Helis",
    "Aigua Blava",
    "Aigua Xelida",
    "Alaior",
    "Albufeira",
    "Alcaria Cova",
    "Alcudia",
    "Alignan-du-Vent",
    "Ammoudi",
    "Anthousa Village",
    "Antipata",
    "Apano Stalos",
    "Apolisi",
    "Arcos de la Frontera",
    "Arcozelo",
    "Aspra",
    "Assos",
    "Aumes",
    "Balcon al Mar",
    "Baleyssagues",
    "Banyalbufar",
    "Barbati",
    "Barral",
    "Bárrio",
    "Bataji",
    "Begur",
    "Benamahoma",
    "Bessan",
    "Binibeca",
    "Binidali",
    "Biot",
    "Bolsena",
    "Boukari",
    "Buger",
    "Cabração",
    "Cabrières d'Avignon",
    "Cala Canyelles",
    "Cala d'Or",
    "Cala Egos",
    "Cala Llonga",
    "Cala Mondrago",
    "Cala Morell",
    "Cala Sa Nau",
    "Cala Sa Nau/Cala Mitjana",
    "Cala San Vicenç",
    "Calella/Llafranc",
    "Calheiros",
    "Callas",
    "Caromb",
    "Castelfiorentino",
    "Castell-Platja d'Aro",
    "Castelnau-de-Guers",
    "Castelnau-de-Lévis",
    "Castelnau-de-Montmiral",
    "Castiglion Fiorentino",
    "Castillonnès",
    "Caux",
    "Cazals",
    "Ceilan",
    "Collobrières",
    "Combarro",
    "Costa Nova",
    "Coves Noves",
    "Cumbre del Sol",
    "Defaranata",
    "Dévillac",
    "Dragotina",
    "Dubravka",
    "Duravel",
    "El Bosque",
    "El Gastor",
    "El Portet",
    "El Santiscal",
    "Estoi",
    "Eygalières",
    "Facha",
    "Felanitx",
    "Fiskardo",
    "Floressas",
    "Fontao",
    "Gaglietole",
    "Gale",
    "Gastouri",
    "Gemeira",
    "Gerakas",
    "Gialova",
    "Giove",
    "Gondufe",
    "Gordes",
    "Gouvia",
    "Grasse",
    "Grazalema",
    "Grimaud",
    "Gruda",
    "Guia",
    "Halikounas",
    "Hio",
    "Islamlar",
    "Jesus Pobre",
    "Kaligata",
    "Kalipado",
    "Kalkan",
    "Karavados",
    "Kas Peninsula",
    "Kassiopi",
    "Katapodata",
    "Katomeri",
    "Katsarata",
    "Kerasia",
    "Khalikerí",
    "Kokkini OR",
    "Korakies",
    "La Borie Blanche",
    "La Font",
    "La Fouillade",
    "La Pera",
    "Lagopodo",
    "Landerrouat",
    "Le Brel",
    "Le Fleix",
    "Le Tignet",
    "Lefkada Town",
    "Lézignan la Cèbe",
    "Libreros",
    "Llafranc",
    "Loulé",
    "Lourdas",
    "Loutses",
    "Lucignana",
    "Ludo",
    "Lugar da Marasca",
    "Maganos",
    "Maheri",
    "Makryotika",
    "Maleme",
    "Malhão",
    "Margon",
    "Martel",
    "Martillac",
    "Maruzini",
    "Maussane Les Alpilles",
    "Mercatale",
    "Metaxata",
    "Mihanići",
    "Mikri Mantineia",
    "Minies",
    "Mirandol-Bourgnounac",
    "Moledo do Minho",
    "Monclar-de-Quercy",
    "Mont Ras",
    "Montagnac-sur-Lède",
    "Montauroux",
    "Montcuq",
    "Montgo National Park",
    "Moreira",
    "Moreira do Lima",
    "Mosende",
    "Moussata",
    "Nasce",
    "Nissaki",
    "Nydri",
    "O Barro",
    "Oia",
    "Olhos d'Agua",
    "Orgiva",
    "Paciano",
    "Paderne",
    "Palmeira de Faro",
    "Paradou",
    "Parentis-en-Born",
    "Parga Town",
    "Petalidi",
    "Peymeinade",
    "Pézenas",
    "Pianello",
    "Pico de Regalados",
    "Pino Sol",
    "Pirgi",
    "Platanias",
    "Platja de Pals",
    "Playa de Limens",
    "Playa de Pintens",
    "Playa de Santa Marta",
    "Polemarchi",
    "Pollenca",
    "Pomport",
    "Ponte de Lima",
    "Port de Pollenca",
    "Portocolom",
    "Pozzo della Chiana",
    "Prats-du-Périgord",
    "Quinta do Rosal",
    "Radetici",
    "Radici",
    "Raxó",
    "Regencós",
    "Riba de Ancora",
    "Rieux-Minervois",
    "Roche Viejo",
    "Roda",
    "Ronda",
    "Roussillon",
    "Rustrel",
    "Saint Antonin-du-Var",
    "Saint Didier",
    "Saint Maurice-de-Lestapel",
    "Saint Rémy de Provence",
    "Salvagnac",
    "San Gimignano",
    "San Jose del Valle",
    "San Leo Bastia",
    "San Pancrazio",
    "Sant Lluis",
    "Sant Marti d'Empuries",
    "Santa Bárbara de Nexe",
    "Santa Catarina Fonte do Bispo",
    "Santa Margalida",
    "Santiago de Compostela",
    "Sao Rafael",
    "São Rafael",
    "Sarlata",
    "Ses Mongetes",
    "Seyches",
    "Sisan",
    "Sivota",
    "Son Bou",
    "Son Parc",
    "Son Vent",
    "Spartia",
    "Spartohori",
    "St André-de-Najac",
    "St Cézaire sur Siagne",
    "St Paul de Vence",
    "Stancija Blek",
    "Sveti Lovrec",
    "Tamariu",
    "Tavronitis Beach",
    "Teulada/Moraira",
    "The Pine Walk",
    "Tinjan",
    "Torre Soli (Son Bou)",
    "Torregentile",
    "Travassos",
    "Tsoukalades",
    "Valbonne",
    "Vall de Colonya",
    "Vanato",
    "Vasilikades",
    "Vasiliki",
    "Vasilikos",
    "Vatos",
    "Vejer de la Frontera",
    "Venade",
    "Vence",
    "Vigo",
    "Vila de Prado",
    "Vilacoba",
    "Vilamoura",
    "Vilariño de Arriba",
    "Vilas",
    "Villars",
    "Viros",
    "Visnjan",
    "Vitorino das Donas",
    "Xabia (Javea)",
    "Zahora"
  ]
};
